version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:20.9
    steps:
      - add_ssh_keys:
          fingerprints:
            # Fingerprint of the deploy key
            - "SHA256:ZZ5iIB1IIyOGTIoGlhGNhiP+QRd96//qxPmUwwucWNQ" 
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Execute tests
          command: npm test

workflows:
  version: 2
  test-workflow:
    jobs:
      - test:
          filters:
            branches:
              only: test
              # So CircleCI can take into account pushes
              # - develop  

