# .circleci/config.yml
version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:20.9
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm test

workflows:
  version: 2
  test-workflow:
    jobs:
      - test:
          filters:
            branches:
              only:
                - develop
