# .github/workflows/dispatch-merge.yml
name: Dispatch merge-develop-to-test

on:
  status:
    types: [success]  # écoute les status checks

jobs:
  dispatch:
    runs-on: ubuntu-latest
    # Ne s'exécute que pour le job CircleCI sur develop
    if: >
      github.event.context == 'ci/circleci: test-workflow'
      && startsWith(github.event.sha, github.sha)
      && github.ref == 'refs/heads/develop'
    steps:
      - name: Fire repository_dispatch → trigger-merge
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_PAT }}          
          repository: mayados/placopro           # owner/name
          event-type: trigger-merge
          client-payload: |
            { "ref": "refs/heads/develop" }
